# Generated by Django 4.0.4 on 2022-04-16 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="PlayerMatchStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pubg.match"),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pubg.player"
                    ),
                ),
            ],
            options={
                "unique_together": {("player", "match")},
            },
        ),
        migrations.AddField(
            model_name="player",
            name="matches",
            field=models.ManyToManyField(through="pubg.PlayerMatchStats", to="pubg.match"),
        ),
    ]
