# Generated by Django 4.0.4 on 2022-04-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_forsen',
            field=models.BooleanField(default=False),
        ),
    ]
