# Generated by Django 4.0.4 on 2022-04-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubg', '0002_player_is_forsen'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatchstats',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
