# Generated by Django 4.0.4 on 2022-04-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pubg", "0011_match_forsen_died_to_cause"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="deaths",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="games_sniped",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="kills",
            field=models.IntegerField(default=0),
        ),
    ]
