# Generated by Django 4.0.4 on 2022-05-27 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pubg", "0013_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="last_update",
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 1, 0, 0)),
        ),
    ]
