# Generated by Django 4.0.4 on 2022-06-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pubg", "0017_player_killscore"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["name"], name="pubg_player_name_f5804c_idx"),
        ),
    ]
